### ISSUE TITLE
谷歌云 搭建v2ray+ws+tls 失败

### ISSUE THREAD

**Issue by dong1818** [233boy/v2ray#1028]
每当输入域名的时候都会提示以下错误:

"请输入一个 正确的域名，一定一定一定要正确，不！能！出！错！
(例如：233blog.com): [weilegogo.tk](url)

 你的域名 = [weilegogo.tk](url)
----------------------------------------------------------------
/dev/fd/63: line 889: wget: command not found
/dev/fd/63: line 890: wget: command not found
 获取IP失败, 这垃圾小鸡扔了吧！"

三种指令的V2ray一键脚本都试过都是出现一样的错误。
bash <(curl -sL https://233v2.com/v2.sh)
bash <(curl -s -L https://233v2.com/v2ray.sh)
bash <(curl -sL https://git.io/v2ray.sh) online old

也尝试过先安装curl 这条指令 apt-get update -y && apt-get install curl -y   然后再安装V2ray一键脚本也是出现一样的错误。

域名我也Ping过 都是通的。我也尝试了好几个不同的域名也不行。
请大佬帮我看下 问题出在哪里 谢谢了

![cloudflare](https://user-images.githubusercontent.com/120270263/206866330-65c99d00-7a03-4404-913d-dd68f2fca166.PNG)

**Comment by crazypeace** [comment]
你用微信扫一扫翻译一下，报错信息是说 wget: 没有找到这个命令
所以你用 apt install -y wget 安装一下这个命令，再跑脚本。

**Comment by crazypeace** [comment]
再不行就换个脚本。
你的操作系统是 Debian 吗？

**Comment by dong1818** [comment]
感谢 crazypeace大佬的指点 .问题终于解决了。非常感谢

**Comment by dong1818** [comment]
感谢 crazypeace大佬的指点 .问题终于解决了。非常感谢

**Comment by crazypeace** [comment]
不客气。很高兴帮到你 ：）

**Comment by msh101162** [comment]
**hi, I'm from Iran
The v2ray protocol is not working for several days
Because of the disorder they put on Cloudflare
Is it possible to use another site instead of Cloudflare?
A site that has free dns and allows a record
I had another question
Wstunell protocol works well in Iran now
Is there a script that can start wstunell protocol on the server?
Can you please help... the most extreme filtering is  being implemented in Iran😞
