### ISSUE TITLE
v2ray.sh + v2rayN.exe 出现 500 Internal Privoxy Error

### ISSUE THREAD

**Issue by jmyz0455** [233boy/v2ray#228]
大家好，本人根据 *https://github.com/233boy/v2ray/wiki* 提供的 **bash <(curl -s -L https://git.io/v2ray.sh)** 命令，下载一键脚本到 CentOS 7.6 的 VPS 上。运行并全程回车安装，取得 vmess URL 后用 **netstat -lt** 和 **systemctl status v2ray** 确认 v2ray 的端口和进程已经开启。

然后在 Windows10 下载并解压 *https://github.com/v2ray/v2ray-core/releases* 的 **v2ray-windows-64.zip** 和 *https://github.com/2dust/v2rayN/releases* 的 **v2rayN.zip** 到同一目录里。管理员权限运行 **v2rayN.exe** 并成功导入 vmess URL。VPS 的 ip 可被 v2rayN 测网速和测延迟。**v2rayN 设置全局代理并点击开启 http 代理**。同时软件的控制台显示：
```shell
配置成功
Vmess-helloworld(myip:myport)
启动服务(2019/6/11 19:06:11)......
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
```
以上操作过后，使用 Chome 访问 google.com 却提示：

>500 Internal Privoxy Error
>Privoxy encountered an error while processing your request:
>Could not load template file no-server-data or one of its included components.
>Please contact your proxy administrator.
>If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

碍于无法访问外网搜索引擎，只能通过 bing 和 baidu 找到可能与服务器与客户端时间不同步有关，但是 Xshell 连接 VPS 后输入 **date "+%Y-%m-%d %H:%M:%S"** 和电脑 PowerShell 输入 **Get-Date -Format "yyy-MM-dd HH:mm:ss"** 均显示时间差小于 1s 。其他类似相关的问题搜索不到。Verror.log 应该设置日志等级为什么会比较容易追踪问题？

我是个没成功搭建过 v2 的新人，多番自查无果，觉得这里人多前来讨教，请轻喷。希望各位提供解决和排查的思路，谢谢。

**Comment by Zxilly** [comment]
你拿v2rayn的那个测速跑一下，跑完了把下面的框里面的东西发出来

**Comment by Zxilly** [comment]
那个myip:mpport是你改的还是你就这么填的。。。

**Comment by Zxilly** [comment]
这个500一般是压根没连上服务器或者你访问的网站已经莫得

**Comment by vicessprites** [comment]
> 
> 
> 这个500一般是压根没连上服务器或者你访问的网站已经莫得

我也是同样错误，

~~点测速之后的错误
启动服务(2019/6/14 10:07:50)......
http://speedtest-sfo2.digitalocean.com/10mb.test
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
2019/06/14 10:07:51 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/14 10:07:51 tcp:127.0.0.1:7541 accepted tcp:speedtest-sfo2.digitalocean.com:80 
The remote server returned an error: (500) Internal Server Error.

域名NS设置到cl，
cl里面overview是active，
crypto  “Universal SSL Status Active Certificate”
DNS点亮DNS and HTTP proxy(CDN)
analytics里面traffic大部分是Uncached Requests，不知道哪里出错了

**Comment by vicessprites** [comment]
> 
> 
> 这个500一般是压根没连上服务器或者你访问的网站已经莫得
firewall和iptalbes也都是关闭的

**Comment by jmyz0455** [comment]
> 你拿v2rayn的那个测速跑一下，跑完了把下面的框里面的东西发出来

1、测速不行，报了一大堆错，跟没连上的错误一样。
2、我不是这么填的，发上来当然要有些修改嘛。
3、我访问的就是 www.google.com

不过现在问题已经找到，原来 Vultr 的 CentOS 是默认开启防火墙的，这点我是真不知道，用 `systemctl stop firewalld; systemctl disable firewalld` 关闭并禁用防火墙即可。

感谢 https://github.com/v2ray/v2ray-core/issues/619 这位老哥的提醒，mark 一个给后来者提醒。

**Comment by BiggerHao** [comment]
我也出现了这个问题，看了这个issue以后自动更新了日期和时间，然后就可以正常连接了。因为我这台是新电脑，还没来得及设置时间:cry:

**Comment by tinsn** [comment]
同样出现这个问题，是windows的系统时间没设置没同步。更新系统时间后ok了。

**Comment by SR023** [comment]
说下我遇到的情况，win10导入时是用的某app自带的二维码分享保存的图片。然后报500  Internal Privoxy Error，后来用文本导入的方式就解决了。

**Comment by wa008** [comment]
> > 你拿v2rayn的那个测速跑一下，跑完了把下面的框里面的东西发出来
> 
> 1、测速不行，报了一大堆错，跟没连上的错误一样。
> 2、我不是这么填的，发上来当然要有些修改嘛。
> 3、我访问的就是 [www.google.com](http://www.google.com)
> 
> 不过现在问题已经找到，原来 Vultr 的 CentOS 是默认开启防火墙的，这点我是真不知道，用 `systemctl stop firewalld; systemctl disable firewalld` 关闭并禁用防火墙即可。
> 
> 感谢 [v2ray/v2ray-core#619](https://github.com/v2ray/v2ray-core/issues/619) 这位老哥的提醒，mark 一个给后来者提醒。

点赞

**Comment by iqiqiqi** [comment]
同样的500错误，V2rayN测试如下所示：
`2020/04/28 08:29:12 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:29:18 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:29:19 tcp:127.0.0.1:51517 accepted tcp:beacons.gvt2.com:443 [proxy] 
2020/04/28 08:29:19 tcp:127.0.0.1:51516 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/04/28 08:29:19 tcp:127.0.0.1:51519 accepted tcp:beacons2.gvt2.com:443 [proxy] 
2020/04/28 08:29:20 tcp:127.0.0.1:51524 accepted tcp:www.youtube.com:443 [proxy] 
2020/04/28 08:29:20 tcp:127.0.0.1:51525 accepted tcp:www.youtube.com:443 [proxy] 
2020/04/28 08:29:20 tcp:127.0.0.1:51527 accepted tcp:fonts.googleapis.com:443 [proxy] 
2020/04/28 08:29:20 tcp:127.0.0.1:51526 accepted tcp:i.ytimg.com:443 [proxy] 
2020/04/28 08:29:35 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:29:41 tcp:127.0.0.1:51538 accepted tcp:www.youtube.com:443 [proxy] 
2020/04/28 08:29:41 tcp:127.0.0.1:51539 accepted tcp:www.youtube.com:443 [proxy] 
2020/04/28 08:29:41 tcp:127.0.0.1:51541 accepted tcp:i.ytimg.com:443 [proxy] 
2020/04/28 08:29:41 tcp:127.0.0.1:51542 accepted tcp:fonts.googleapis.com:443 [proxy] 
2020/04/28 08:30:00 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:30:01 tcp:127.0.0.1:51551 accepted tcp:accounts.google.com:443 [proxy] 
2020/04/28 08:30:01 tcp:127.0.0.1:51550 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/04/28 08:30:01 tcp:127.0.0.1:51554 accepted tcp:beacons.gvt2.com:443 [proxy] 
2020/04/28 08:30:01 tcp:127.0.0.1:51556 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/04/28 08:30:14 tcp:127.0.0.1:51563 accepted tcp:accounts.google.com:443 [proxy] 
2020/04/28 08:30:17 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:30:18 tcp:127.0.0.1:51565 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/04/28 08:30:22 tcp:127.0.0.1:51570 accepted tcp:update.minipage.2345.cc:80 [proxy] 
2020/04/28 08:30:36 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:30:37 tcp:127.0.0.1:51577 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/04/28 08:30:37 tcp:127.0.0.1:51580 accepted tcp:beacons.gvt2.com:443 [proxy] 
2020/04/28 08:30:37 tcp:127.0.0.1:51581 accepted tcp:google.com:443 [proxy] 
2020/04/28 08:30:37 tcp:127.0.0.1:51584 accepted tcp:beacons.gvt2.com:443 [proxy] 
2020/04/28 08:30:37 tcp:127.0.0.1:51586 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/04/28 08:30:37 tcp:127.0.0.1:51588 accepted tcp:update.minipage.2345.cc:80 [proxy] 
2020/04/28 08:30:54 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 108.61.162.242:27769: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 08:30:55 tcp:127.0.0.1:51595 accepted tcp:beacons.gvt2.com:443 [proxy] 
2020/04/28 08:30:57 tcp:127.0.0.1:51598 accepted tcp:ts.minipage.2345.cc:80 [proxy] `

**Comment by Bblackc** [comment]
Same error as the above , but it is different issues

v2ray.com/core/common/retry: all retry attempts failed
2021/01/27 10:34:29 tcp:127.0.0.1:57015 accepted tcp:clients3.google.com:80 [proxy] 
2021/01/27 10:34:34 [Warning] [2876987199] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp 47.242.235.98:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/27 10:34:36 tcp:127.0.0.1:57018 accepted tcp:clients3.google.com:80 [proxy] 



process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp 47.242.235.98:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/27 10:34:57 tcp:127.0.0.1:57033 accepted tcp:clients3.google.com:80 [proxy] 
2021/01/27 10:35:02 [Warning] [2747903202] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp 47.242.235.98:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/27 10:35:04 tcp:127.0.0.1:57036 accepted tcp:clients3.google.com:80 [proxy] 
2021/01/27 10:35:09 [Warning] [3412931846] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp 47.242.235.98:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/27 10:35:11 tcp:127.0.0.1:57039 accepted tcp:clients3.google.com:80 [proxy] 
2021/01/27 10:35:16 [Warning] [4176896180] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp 47.242.235.98:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://huohao.fun/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2021/01/27 10:35:18 tcp:127.0.0.1:57042 accepted tcp:clients3.google.com:80 [proxy]
