### ISSUE TITLE
你们测试一下 Caddy 还会不会不能运行 (

### ISSUE THREAD

**Issue by 233boy** [233boy/v2ray#318]
😂 😂 😂 😂 😂 

发了一个新的 Fix... 

快看看 Caddy 能不能正常跑起来了，但是我从没出现过不能运行的问题，我无法复现你们出现的问题 (

**Comment by hongzhng** [comment]
just tried a new installation and it works now.  (it was not working yesterday)

**Comment by m4d3bug** [comment]
I have a situation where caddy can't run. Same as the below error.
Because the same deployment was repeated five times on the same VPS.
It should be because of the number of certificates, the relevant query results are attached below.
---
https://crt.sh/?q=%m4d3bug.tk
https://community.letsencrypt.org/t/error-429-too-many-registrations-for-this-ip/83204/21
---

**Comment by arronyxzhang** [comment]
刚刚试过，可用了。早上还不行的，这次Caddy 能正常跑起来了

**Comment by 233boy** [comment]
> 刚刚试过，可用了。早上还不行的，这次Caddy 能正常跑起来了

真的嘛？？？ 😂

**Comment by 233boy** [comment]
> ## I have a situation where caddy can't run. Same as the below error.
> Because the same deployment was repeated five times on the same VPS.
> It should be because of the number of certificates, the relevant query results are attached below.
> ## https://crt.sh/?q=%m4d3bug.tk
> https://community.letsencrypt.org/t/error-429-too-many-registrations-for-this-ip/83204/21

try use a domain or after wait for a week and try again

**Comment by m4d3bug** [comment]
> > ## I have a situation where caddy can't run. Same as the below error.
> > Because the same deployment was repeated five times on the same VPS.
> > It should be because of the number of certificates, the relevant query results are attached below.
> > ## https://crt.sh/?q=%m4d3bug.tk
> > https://community.letsencrypt.org/t/error-429-too-many-registrations-for-this-ip/83204/21
> 
> try use a domain or after wait for a week and try again

Did it yesterday but no work. I think I should wait until 3 months later because of the certificate validity date.

**Comment by sucrezh** [comment]
Sep 23 09:06:29 vultr.guest caddy[2433]: 2019/09/23 09:06:29 [INFO] acme: Registering account for 34804334592@gmail.com
Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system (attempt 1/3)
Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [INFO] acme: Registering account for 34804334592@gmail.com
Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:  (attempt 2/3)
Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [INFO] acme: Registering account for 34804334592@gmail.com
Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:  (attempt 3/3)
Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:
Sep 23 09:06:31 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Sep 23 09:06:31 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Sep 23 09:06:31 vultr.guest systemd[1]: caddy.service failed.
谁知道我是什么问题，求大佬帮解决，折腾很久了

**Comment by 233boy** [comment]
> Sep 23 09:06:29 vultr.guest caddy[2433]: 2019/09/23 09:06:29 [INFO] acme: Registering account for [34804334592@gmail.com](mailto:34804334592@gmail.com)
> Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system (attempt 1/3)
> Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [INFO] acme: Registering account for [34804334592@gmail.com](mailto:34804334592@gmail.com)
> Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url: (attempt 2/3)
> Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [INFO] acme: Registering account for [34804334592@gmail.com](mailto:34804334592@gmail.com)
> Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url: (attempt 3/3)
> Sep 23 09:06:31 vultr.guest caddy[2433]: 2019/09/23 09:06:31 registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:
> Sep 23 09:06:31 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
> Sep 23 09:06:31 vultr.guest systemd[1]: Unit caddy.service entered failed state.
> Sep 23 09:06:31 vultr.guest systemd[1]: caddy.service failed.
> 谁知道我是什么问题，求大佬帮解决，折腾很久了

我搜索了一下，你应该是域名写错了

**Comment by lowprofileusername** [comment]
caddy 这个状态是正常的么，V2可以跑就是经常出这个错误
Sep 23 12:01:54 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:01:54 http: TLS handshake error from 127.0.0.1:48010:
Sep 23 12:01:54 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:01:54 [ERROR] failed to copy buffer:  readfrom tcp 12
Sep 23 12:01:55 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:01:55 [ERROR] failed to copy buffer:  read tcp 127.0.
Sep 23 12:01:55 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:01:55 [ERROR] failed to copy buffer:  read tcp 127.0.
Sep 23 12:01:56 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:01:56 [ERROR] failed to copy buffer:  readfrom tcp 12
Sep 23 12:02:00 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:02:00 [ERROR] failed to copy buffer:  readfrom tcp 12
Sep 23 12:02:00 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:02:00 [ERROR] failed to copy buffer:  readfrom tcp 12
Sep 23 12:02:01 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:02:01 [ERROR] failed to copy buffer:  readfrom tcp 12
Sep 23 12:02:05 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:02:05 [ERROR] failed to copy buffer:  read tcp 127.0.
Sep 23 12:02:11 VM-e16ebcdc-aa5f-4951-a4f6-dc112da1fbb4 caddy[567]: 2019/09/23 12:02:11 [ERROR] failed to copy buffer:  read tcp 127.0.
z

systemctl status caddy显示不完整
[ERROR] failed to copy buffer:  read tcp 127.0.0.1:58028->127.0.0.1:2333: use of closed network connection

应该是这样的报错

**Comment by 23R3F** [comment]
凡是用centos7安装全都运行不起来， 输入 v2ray status一时显示正在运行，一时显示没有运行
我用Debian 10安装以后，一下子就成功了

**Comment by jpfree** [comment]
能否关闭CADDDY的证书功能，换CF的呢？
不成功貌似都是CADDY的问题

**Comment by 23R3F** [comment]
是的，就是CADDY的问题，我改用debian 10系统再用你的一键脚本就成功了，问题应该出在centos系统中，应该得修改脚本



------------------ 原始邮件 ------------------
发件人: "jpfree"<notifications@github.com>; 
发送时间: 2019年9月23日(星期一) 下午5:52
收件人: "233boy/v2ray"<v2ray@noreply.github.com>; 
抄送: "23R3F"<zeref0@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [233boy/v2ray] 你们测试一下 Caddy 还会不会不能运行 ( (#318)




能否关闭CADDDY的证书功能，换CF的呢？
 不成功貌似都是CADDY的问题

**Comment by tryboy1978** [comment]
> 凡是用centos7安装全都运行不起来， 输入 v2ray status一时显示正在运行，一时显示没有运行
> 我用Debian 10安装以后，一下子就成功了

的确，我原来的是CENTOS7，CADDY就是起不来，现在装了DEBIAN10，就一切正常了。

**Comment by ameue** [comment]
wesocket+TSL 使用caddy：
Redirecting to /bin/systemctl status caddy.service
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 一 2019-09-23 23:45:25 CST; 691ms ago
     Docs: https://caddyserver.com/docs
  Process: 12105 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 12105 (code=exited, status=1/FAILURE)

9月 23 23:45:25 iZj6c7upbhe18wh57tlch1Z systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
9月 23 23:45:25 iZj6c7upbhe18wh57tlch1Z systemd[1]: Unit caddy.service entered failed state.
9月 23 23:45:25 iZj6c7upbhe18wh57tlch1Z systemd[1]: caddy.service failed.

连续刷v2ray status:
[root@iZj6c7upbhe18wh57tlch1Z ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

[root@iZj6c7upbhe18wh57tlch1Z ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

[root@iZj6c7upbhe18wh57tlch1Z ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

[root@iZj6c7upbhe18wh57tlch1Z ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

[root@iZj6c7upbhe18wh57tlch1Z ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

[root@iZj6c7upbhe18wh57tlch1Z ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

**Comment by m4d3bug** [comment]
> 不成功貌似都是CADDY的问题

can't agree with you anymore, please consider this approach. @233boy

**Comment by ntgeralt** [comment]
pve下的debian10，运行一键脚本后，caddy不工作：
'
root@18775-panelV2:~# service caddy status
* caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-02-24 05:18:26 CST; 1s ago
     Docs: https://caddyserver.com/docs
  Process: 404 ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=
 Main PID: 404 (code=exited, status=226/NAMESPACE)

Feb 24 05:18:26 18775-panelV2 systemd[1]: Started Caddy HTTP/2 web server.
Feb 24 05:18:26 18775-panelV2 systemd[404]: caddy.service: Failed to set up mount namespacing: Permission denied
Feb 24 05:18:26 18775-panelV2 systemd[404]: caddy.service: Failed at step NAMESPACE spawning /usr/local/bin/caddy: Permission denied
Feb 24 05:18:26 18775-panelV2 systemd[1]: caddy.service: Main process exited, code=exited, status=226/NAMESPACE
Feb 24 05:18:26 18775-panelV2 systemd[1]: caddy.service: Failed with result 'exit-code'.

'
