### ISSUE TITLE
Caddy 状态: 未在运行，后查看状态，这怎么办啊。

### ISSUE THREAD

**Issue by dbguo** [233boy/v2ray#471]
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-02-07 20:44:56 CST; 4min 43s ago
     Docs: https://caddyserver.com/docs
  Process: 3964 ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/
 Main PID: 3964 (code=exited, status=1/FAILURE)

Feb 07 20:44:52 dbguo caddy[3964]: By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
Feb 07 20:44:52 dbguo caddy[3964]:   
Feb 07 20:44:52 dbguo caddy[3964]: Please enter your email address to signify agreement and to be notified
Feb 07 20:44:52 dbguo caddy[3964]: in case of issues. You can leave it blank, but we don't recommend it.
Feb 07 20:44:52 dbguo caddy[3964]:   Email address: [ERROR] Making new certificate manager: get directory at 'https://acme-v02.api.
Feb 07 20:44:53 dbguo caddy[3964]: [ERROR] Making new certificate manager: get directory at 'https://acme-v02.api.letsencrypt.org/d
Feb 07 20:44:55 dbguo caddy[3964]: [ERROR] Making new certificate manager: get directory at 'https://acme-v02.api.letsencrypt.org/d
Feb 07 20:44:56 dbguo systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 20:44:56 dbguo systemd[1]: caddy.service: Unit entered failed state.
Feb 07 20:44:56 dbguo systemd[1]: caddy.service: Failed with result 'exit-code'.

**Comment by jackrong** [comment]
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-02-15 21:38:39 CST; 1min 25s ago
     Docs: https://caddyserver.com/docs
  Process: 3609 ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 3609 (code=exited, status=1/FAILURE)

Feb 15 21:38:35 v136628.kvm.u57759 caddy[3609]: 2020/02/15 21:38:35 [INFO] [cs.max20s.xyz] acme: Obtaining bundled SAN certificate
Feb 15 21:38:35 v136628.kvm.u57759 caddy[3609]: [ERROR][cs.max20s.xyz] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 1/3; challenge=http-01)
Feb 15 21:38:36 v136628.kvm.u57759 caddy[3609]: 2020/02/15 21:38:36 [INFO] [cs.max20s.xyz] acme: Obtaining bundled SAN certificate
Feb 15 21:38:37 v136628.kvm.u57759 caddy[3609]: [ERROR][cs.max20s.xyz] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 2/3; challenge=http-01)
Feb 15 21:38:38 v136628.kvm.u57759 caddy[3609]: 2020/02/15 21:38:38 [INFO] [cs.max20s.xyz] acme: Obtaining bundled SAN certificate
Feb 15 21:38:38 v136628.kvm.u57759 caddy[3609]: [ERROR][cs.max20s.xyz] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 3/3; challenge=http-01)
Feb 15 21:38:39 v136628.kvm.u57759 caddy[3609]: failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url:
Feb 15 21:38:39 v136628.kvm.u57759 systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Feb 15 21:38:39 v136628.kvm.u57759 systemd[1]: Unit caddy.service entered failed state.
Feb 15 21:38:39 v136628.kvm.u57759 systemd[1]: caddy.service failed.

**Comment by jackrong** [comment]
好奇怪，这是什么问题。
