### ISSUE TITLE
chmod: cannot access ‘/usr/bin/v2ray/v2ctl’: No such file or directory

### ISSUE THREAD

**Issue by 572302680** [233boy/v2ray#935]
bash <(curl -s -L https://git.io/v2ray.sh)
使用上面的脚本安装
安装完成不能正常启动
Archive:  /tmp/v2ray.zip
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/vpoint_vmess_freedom.json  
  inflating: /usr/bin/v2ray/vpoint_socks_vmess.json  
  inflating: /usr/bin/v2ray/config.json  
   creating: /usr/bin/v2ray/systemd/
   creating: /usr/bin/v2ray/systemd/system/
  inflating: /usr/bin/v2ray/systemd/system/v2ray.service  
  inflating: /usr/bin/v2ray/systemd/system/v2ray@.service  
  inflating: /usr/bin/v2ray/v2ray    
  inflating: /usr/bin/v2ray/geoip-only-cn-private.dat  
chmod: cannot access ‘/usr/bin/v2ray/v2ctl’: No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/v2ray.service to /etc/systemd/system/v2ray.service.

**Comment by 233boy** [comment]
直接执行， v2ray reinstall 
重装脚本看看

**Comment by huixing9294** [comment]
看了下安装过程，发现最新5.0下载解压后没有压根v2ctl这个文件。版本回退到v4.45.2，恢复正常了。

**Comment by Nyka2022** [comment]
This issue happens if you use english installer.
you can reproduce by running 
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/shell/install_en.sh" && chmod 700 /root/install_en.sh && mv /root/install_en.sh /root/install.sh && /root/install.sh
and install v2core.
