### ISSUE TITLE
3.63 脚本可以安装，安装后服务也在运行，但是还是连不通

### ISSUE THREAD

**Issue by JenryMa** [233boy/v2ray#957]
![image](https://user-images.githubusercontent.com/49137644/194714089-50a76f68-34df-4e04-b5fc-7d0488bc5cef.png)

手机客户端显示： context deadline exceeded.

**Comment by JenryMa** [comment]
![image](https://user-images.githubusercontent.com/49137644/194714184-124914ca-3cd3-4ca5-bb40-77908319194b.png)

**Comment by alexxiang-1990** [comment]
相同的问题，

 当前 V2Ray 版本: v5.1.0  /  当前 V2Ray 管理脚本版本: v3.63

● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: active (running) since 一 2022-10-10 13:45:16 CST; 10min ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
 Main PID: 2079 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─2079 /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json

10月 10 13:45:16 LOS-8 systemd[1]: Started V2Ray Service.
10月 10 13:45:16 LOS-8 env[2079]: V2Ray 5.1.0 (V2Fly, a community-driven e...4)
10月 10 13:45:16 LOS-8 env[2079]: A unified platform for anti-censorship.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by alexxiang-1990** [comment]
> ![image](https://user-images.githubusercontent.com/49137644/194714184-124914ca-3cd3-4ca5-bb40-77908319194b.png)

你把协议改成mKCP-dtls试试看，我改了就可以用了

**Comment by JenryMa** [comment]
> > ![image](https://user-images.githubusercontent.com/49137644/194714184-124914ca-3cd3-4ca5-bb40-77908319194b.png)
> 
> 你把协议改成mKCP-dtls试试看，我改了就可以用了

试过了，还是不行。。

**Comment by erickingxu** [comment]
有解决方案吗？
现在很多人遇到运行v2ray服务正常，但是客户端就是连不上，一测试连接就显示context deadline exceeded.试了各种网上推荐的方案，依旧无解。

**Comment by JenryMa** [comment]
无解
